### ISSUE TITLE
ShopCompanion broken in Firefox Nightly 41

### ISSUE THREAD

**Issue by cpeterso** [ShopCompanion/shop-companion#1]
The ShopCompanion add-on is broken in Firefox Nightly 41 because the add-on's bootstrap.js (from Scriptify) uses a SpiderMonkey-specific JavaScript feature that has been removed ("let expressions"):

https://bugzilla.mozilla.org/show_bug.cgi?id=1023609

**Comment by ShopCompanion** [comment]
Fixed with update to Scriptify 0.2.8 in 0.28.1

**Comment by cpeterso** [comment]
Thanks!
